config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :users, only: [:new, :create, :show]
  resource :session, only: [:new, :create, :destroy]

  resources :bands do
    resources :albums, only: [:new]
  end

  resources :albums, except: [:new, :index]
end

app/models/album.rb
# == Schema Information
#
# Table name: albums
#
#  id         :bigint(8)        not null, primary key
#  title      :string           not null
#  year       :integer          not null
#  band_id    :integer          not null
#  type       :string(1)        not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Album < ApplicationRecord
  validates :band_id, presence: true
  validates :title, :year, :type, presence: true

  belongs_to :band,
  foreign_key: :band_id,
  class_name: :Band

  has_many :tracks,
  foreign_key: :album_id,
  class_name: :Track
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/band.rb
# == Schema Information
#
# Table name: bands
#
#  id         :bigint(8)        not null, primary key
#  name       :string           not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Band < ApplicationRecord
  validates :name, presence: true

  has_many :albums,
  foreign_key: :band_id,
  class_name: :Album

  has_many :tracks,
  through: :albums,
  source: :tracks


end

app/models/track.rb
# == Schema Information
#
# Table name: tracks
#
#  id         :bigint(8)        not null, primary key
#  title      :string           not null
#  ord        :integer          not null
#  album_id   :integer          not null
#  lyrics     :text
#  type       :string(1)        not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Track < ApplicationRecord
  validates :title, :ord, :type, presence: true
  validates :album_id, presence: true

  belongs_to :album,
  foreign_key: :album_id,
  class_name: :Album
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :bigint(8)        not null, primary key
#  email           :string           not null
#  password_digest :string           not null
#  session_token   :string           not null
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class User < ApplicationRecord
  validates :email, presence: true, uniqueness: true
  validates :password_digest, :session_token, presence: true
  validates :password, length: { minimum: 6, allow_nil: true }

  attr_reader :password

  after_initialize :ensure_session_token

  def self.find_by_credentials(email, password)
    user = User.find_by(email: email)
    user && user.is_password?(password) ? user : nil
  end

  def self.generate_session_token
    SecureRandom.urlsafe_base64(16)
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def reset_session_token!
    self.session_token = User.generate_session_token
    self.save
    self.session_token
  end

  def ensure_session_token
    self.session_token ||= User.generate_session_token
  end

end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController

  def new
    @album = Album.new
  end

  def create
    @album = Album.new(album_params)
    if @band.save
      redirect_to band_url(@band)
    else
      flash.now[:errors] = @band.errors.full_messages
    end
  end

  def album_params
    params.require(:album).permit(:title, :year, :band_id, :type)
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
helper_method :current_user, :logged_in?

  def log_in_user!(user)
    session[:session_token] = user.reset_session_token!
    @current_user = user
  end

  def current_user
    @current_user ||= User.find_by(session_token: session[:session_token])
  end

  def logged_in?
    !!current_user
  end

  def logout
    current_user.reset_session_token!
    session[:session_token] = nil
    @current_user = nil
  end
end

app/controllers/bands_controller.rb
class BandsController < ApplicationController

  def index
    @bands = Band.all
  end

  def new
    @band = Band.new
    render :new
  end

  def create
    @band = Band.new(band_params)
    if @band.save
      redirect_to band_url(@band)
    else
      flash.now[:errors] = @band.errors.full_messages
    end
  end

  def show
    @band = Band.find(params[:id])
    render :show
  end

  def edit
    @band = Band.find(params[:id])
    render :edit
  end

  def update
    @band = Band.find(params[:id])
    if @band.update_attributes(band_params)
      redirect_to band_url(@band)
    else
      flash[:errors] = @band.errors.full_messages
      render :edit
    end
  end

  def destroy
    @band = Band.find(params[:id])
    @band.destroy!
    redirect_to bands_url
  end

  private

  def band_params
    params.require(:band).permit(:name)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new

  end

  def create
    @user = User.find_by_credentials(params[:user][:email], params[:user][:password])
    if @user
      log_in_user!(@user)
      redirect_to user_url(@user)
    else
      flash.now[:errors] = "Invalid usename/password"
      redirect_to new_session_url
    end
  end

  def destroy
    logout
    render :new
  end
end

app/controllers/tracks_controller.rb
class TracksController < ApplicationController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in_user!(@user)
      redirect_to user_url(@user)
    else
      flash[:errors] = @user.errors.full_messages
    end
  end

  def show
    @user = current_user
  end

  private

  def user_params
    params.require(:user).permit(:email, :password)
  end



end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bands_helper.rb
module BandsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tracks_helper.rb
module TracksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/bands/edit.html.erb
<h1>Edit a Band</h1>

<form action="<%= band_url(@band) %>" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <input type="hidden" name="_method" value="patch">

  <label for="name">Name of the Band</label>
  <input id="name" type="text" name="band[name]" value="<%= @band.name %>">
  <br>
  <br>

  <input type="submit" value="Edit Name">

</form>

app/views/bands/index.html.erb
<h1>This is the list of all bands</h1>

<% @bands.each do |band| %>
  <a class="band_link" href="<%= band_url(band) %>"><%= band.name %></a>
  <br>
<% end %>

<a class= "create_band" href="<%= new_band_url %>">Create a band</a>

app/views/bands/new.html.erb
<h1>Create a Band</h1>

<form action="<%= bands_url %>" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

  <label for="name">Name of the Band</label>
  <input id="name" type="text" name="band[name]" value="<%= @band.name %>">
  <br>
  <br>

  <input type="submit" value="Create Band">

</form>

app/views/bands/show.html.erb
<h1><%= @band.name %></h1>

<a href="https://clipartxtras.com/download/eb554ee83b5c7a5f8b04ea0503b268f3a1b3ff94.html"><img src="https://img.clipartxtras.com/78b4558c9585ffa4f550ddf3270567d0_rock-band-silhouette-clipart-the-cliparts-rock-band-clipart-black-and-white_690-347.jpeg" width="690" alt="rock band clipart black and white" /></a>

<form action="<%= edit_band_url(@band) %>" method="get">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

  <input type="submit" value="EDIT NAME">
</form>

<form action="<%= band_url(@band) %>" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <input type="hidden" name="_method" value="delete">

  <input type="submit" value="DELETE BAND">
</form>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<style type="text/css">
  .website_name {
    font-family: helvetica;
    font-size: 60px;
    font-style: bold;
    color: #CC9A2B;
    text-decoration: none;
  }
  .right {
    float: right;
  }

  .left {
    float: left;
  }
  .header_div{
    display: block;
  }
  div {
    display: block;
    text-align: center;
  }
  .div_child {
    margin: auto;
  }
  body {
    background-color: #646464
  }
  h1 {
    color: white;
    font-family: helvetica;
  }

  .button {
    display: block;
    border: 2px solid white;
    border-radius: 10px;
    color: white;
    font-family: sans-serif;
    padding: 5px;
    text-decoration: none;
    background-color: #5CCC4D;
    font-size: 20px;
  }

  .logout_button{
    display: block;
    border: 2px solid white;
    border-radius: 10px;
    color: white;
    font-family: sans-serif;
    padding: 5px;
    text-decoration: none;
    background-color: red;
    font-size: 20px;
  }

  .band_link {
    display: block;
    width: 200px;
    height: 15px;
    border: 2px solid white;
    border-radius: 5px;
    color: white;
    font-family: sans-serif;
    padding: 5px;
    text-decoration: none;
    background-color: red;
    font-size: 20px;
  }

  .create_band {
    display: block;
    width: 150px;
    height: 20px;
    border: 2px solid white;
    border-radius: 5px;
    color: white;
    font-family: sans-serif;
    padding: 5px;
    text-decoration: none;
    background-color: #5CCC4D;
    font-size: 20px;
  }
</style>
  <head>
    <title>MusicApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <header>
    <div class="left">
      <a class= "button" href="<%= bands_url %>">HOME</a>
    </div>

    <div class="header_div">
      <h1 class="website_name">🎵MUSIC APP🎵</h1>
    </div>
  </header>
  <% if current_user.nil? %>
    <div class="right">
      <a class= "button" href="<%= new_session_url %>">LOG IN</a>
      <br>
      <a class= "button" href="<%= new_user_url %>">SIGN UP</a>
    </div>

  <% else %>
    <div class="right">
      Hi <%= current_user.email %> !
      <form class="" action="<%= session_url %>" method="post">
        <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
        <input type="hidden" name="_method" value="delete">
        <input class="logout_button" type="submit" value="Log out">
      </form>
    </div>

  <% end %>

  <div>
    <div class="div_child">
      <body>
        <%= yield %>
      </body>
    </div>
  </div>
</html>

app/views/users/new.html.erb
<h1>SIGN UP</h1>

<form action="<%= users_url %>" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

  <label for="email">Email</label>
  <input id="email" type="text" name="user[email]" value="<%= @user.email %>">
  <br>
  <br>

  <label for="password">Password</label>
  <input id="password" type="password" name="user[password]" value="<%= @user.password %>">
  <br>
  <br>

  <input type="submit" value="Sign up">

</form>

app/views/users/show.html.erb
<h1>User profile</h1>

<%= @user.email %>